name: 'Carthage workaround'
description: 'Action that allows Carthage to build using Xcode without M1 architecture'
inputs:
  action:
    description: 'Carthage action that should be performed'
    required: true
  force:
    description: 'Force run Carthage workaround script even though it might not be necessary (e.g. building using Xcode 11)'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'index.js'